on: # yamllint disable-line rule:truthy
  push:
    branches: ["main"]

name: Create container image

jobs:
  call-image-build-workflow:
    uses: fmidev/github-actions-workflows/.github/workflows/imagebuild-workflow.yaml@main
    with:
      image_name: kairos_inference
      image_test_command: python3 /kairos_inference/inference.py --help
    secrets:
      QUAY_USER: ${{ secrets.QUAY_USER }}
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}